---
- name: put "vr" function into bashrc
  # comment has random string to ease later identification
  blockinfile:
    dest: /etc/bash.bashrc
    backup: yes
    marker: "# {mark} created by ansible 4bb8a80471de7"
    block: |
      function vr() {
        if [ -d ${HOME}/ros/freemovr-kinetic/ ]; then
          source ${HOME}/ros/freemovr-kinetic/devel/setup.bash
        fi
      }

- name: Ensure freemovr-kinetic.rosinstall is available
  copy: src=freemovr-kinetic.rosinstall dest=/etc/ros/freemovr-kinetic.rosinstall owner=root group=root mode=0644

- name: copy installer script
  copy: src=make-freemovr-workspace.sh dest=/opt/ros/workspace-installers/kinetic/make-freemovr-workspace.sh owner=root group=root mode=0755
