- name: Ensure rosdep sources dir exists
  file: path=/etc/ros/rosdep/sources.list.d state=directory mode=0755 owner=root group=root

- name: Ensure strawlab rosdep URL is included into rosdep sources
  copy: src=35-strawlab-indigo.list dest=/etc/ros/rosdep/sources.list.d/35-strawlab-indigo.list owner=root group=root mode=0644

- name: Ensure freemovr-engine-indigo.rosinstall is available
  copy: src=freemovr-engine-indigo.rosinstall dest=/etc/ros/freemovr-engine-indigo.rosinstall owner=root group=root mode=0644

- name: install sudo command
  # This is required by `rosdep install`
  apt: name=sudo state=installed

- name: install wstool command
  # This is required for `wstool`
  apt: name=python-wstool state=installed

- name: Ensure workspace installer dir exists
  file: path=/opt/ros/workspace-installers/indigo/ state=directory mode=0755 owner=root group=root

- name: copy installer script
  copy: src=make-freemovr-engine-workspace.sh dest=/opt/ros/workspace-installers/indigo/make-freemovr-engine-workspace.sh owner=root group=root mode=0755
